// Code generated by go-mavlink/mavgen
// DO NOT EDIT!

package mavlink

import (
	"errors"
	"github.com/asmyasnikov/go-mavlink/x25"
	"io"
	"log"
	"runtime"
	"strconv"
	"sync"
	"time"
)

const (
	magicNumber = 0xfd
	hdrLen      = 10
)

type MAVLINK_PARSE_STATE int

// MAVLINK_PARSE_STATES
const (
	MAVLINK_PARSE_STATE_UNINIT             MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_IDLE               MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_STX            MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_LENGTH         MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_INCOMPAT_FLAGS MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_COMPAT_FLAGS   MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_SEQ            MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_SYSID          MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_COMPID         MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_MSGID1         MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_MSGID2         MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_MSGID3         MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_PAYLOAD        MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_GOT_CRC1           MAVLINK_PARSE_STATE = iota
	MAVLINK_PARSE_STATE_OK                 MAVLINK_PARSE_STATE = iota
)

var (
	// ErrUnknownMsgID define
	ErrUnknownMsgID = errors.New("unknown msg id")
	// ErrCrcFail define
	ErrCrcFail = errors.New("checksum did not match")
	// ErrNoNewData define
	ErrNoNewData = errors.New("No new data")
)

// MessageID typedef
type MessageID uint32

// Message is a basic type for encoding/decoding mavlink messages.
// use the Pack() and Unpack() routines on specific message
// types to convert them to/from the Packet type.
type Message interface {
	Pack(*Packet) error
	Unpack(*Packet) error
	MsgID() MessageID
	MsgName() string
}

// Packet is a wire type for encoding/decoding mavlink messages.
// use the ToPacket() and FromPacket() routines on specific message
// types to convert them to/from the Message type.
type Packet struct {
	InCompatFlags uint8     // incompat flags
	CompatFlags   uint8     // compat flags
	SeqID         uint8     // Sequence of packet
	SysID         uint8     // ID of message sender system/aircraft
	CompID        uint8     // ID of the message sender component
	MsgID         MessageID // ID of message in payload
	Payload       []byte
	Checksum      uint16
}

// Decoder struct provide decoding processor
type Decoder struct {
	parser    Parser
	CurrSeqID uint8        // last seq id decoded
	Dialects  DialectSlice // dialects that can be decoded
	data      chan []byte
}

// Encoder struct provide encoding processor
type Encoder struct {
	sync.Mutex
	CurrSeqID uint8        // last seq id encoded
	Dialects  DialectSlice // dialects that can be encoded
	data      chan []byte
}

type Parser struct {
	state  MAVLINK_PARSE_STATE
	packet Packet
	crc    *x25.X25
}

func (parser *Parser) parseChar(c byte, dialects DialectSlice) *Packet {
	log.Printf("Call parseChar. Current state %d\n", parser.state)
	switch (parser.state) {
	case MAVLINK_PARSE_STATE_UNINIT:
	case MAVLINK_PARSE_STATE_IDLE:
		log.Println("MAVLINK_PARSE_STATE_UNINIT | MAVLINK_PARSE_STATE_IDLE")
		if c == magicNumber {
			parser.crc = x25.New()
			parser.state = MAVLINK_PARSE_STATE_GOT_STX
		}
	case MAVLINK_PARSE_STATE_GOT_STX:
		log.Println("MAVLINK_PARSE_STATE_GOT_STX")
		parser.packet.Payload = make([]byte, 0, c)
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_LENGTH
	case MAVLINK_PARSE_STATE_GOT_LENGTH:
		log.Println("MAVLINK_PARSE_STATE_GOT_LENGTH")
		parser.packet.InCompatFlags = c
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_INCOMPAT_FLAGS
	case MAVLINK_PARSE_STATE_GOT_INCOMPAT_FLAGS:
		log.Println("MAVLINK_PARSE_STATE_GOT_INCOMPAT_FLAGS")
		parser.packet.CompatFlags = c
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_COMPAT_FLAGS
	case MAVLINK_PARSE_STATE_GOT_COMPAT_FLAGS:
		log.Println("MAVLINK_PARSE_STATE_GOT_COMPAT_FLAGS")
		parser.packet.SeqID = c
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_SEQ
	case MAVLINK_PARSE_STATE_GOT_SEQ:
		log.Println("MAVLINK_PARSE_STATE_GOT_SEQ")
		parser.packet.SysID = c
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_SYSID
	case MAVLINK_PARSE_STATE_GOT_SYSID:
		log.Println("MAVLINK_PARSE_STATE_GOT_SYSID")
		parser.packet.CompID = c
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_COMPID
	case MAVLINK_PARSE_STATE_GOT_COMPID:
		log.Println("MAVLINK_PARSE_STATE_GOT_COMPID")
		parser.packet.MsgID = MessageID(c)
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_MSGID1
	case MAVLINK_PARSE_STATE_GOT_MSGID1:
		log.Println("MAVLINK_PARSE_STATE_GOT_MSGID1")
		parser.packet.MsgID += MessageID(c << 8)
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_MSGID2
	case MAVLINK_PARSE_STATE_GOT_MSGID2:
		log.Println("MAVLINK_PARSE_STATE_GOT_MSGID2")
		parser.packet.MsgID += MessageID(c << 8 * 2)
		parser.crc.WriteByte(c)
		parser.state = MAVLINK_PARSE_STATE_GOT_MSGID3
	case MAVLINK_PARSE_STATE_GOT_MSGID3:
		log.Println("MAVLINK_PARSE_STATE_GOT_MSGID3")
		parser.packet.Payload = append(parser.packet.Payload, c)
		parser.crc.WriteByte(c)
		if len(parser.packet.Payload) == cap(parser.packet.Payload) {
			parser.state = MAVLINK_PARSE_STATE_GOT_PAYLOAD
		}
	case MAVLINK_PARSE_STATE_GOT_PAYLOAD:
		log.Println("MAVLINK_PARSE_STATE_GOT_PAYLOAD")
		// crc extra
		crcExtra, err := dialects.findCrcX(parser.packet.MsgID)
		if err != nil {
			crcExtra = 0
		}
		parser.crc.WriteByte(crcExtra)
		if c != uint8(parser.crc.Sum16()&0xFF) {
			parser.state = MAVLINK_PARSE_STATE_IDLE
		} else {
			parser.state = MAVLINK_PARSE_STATE_GOT_CRC1
		}
	case MAVLINK_PARSE_STATE_GOT_CRC1:
		log.Println("MAVLINK_PARSE_STATE_GOT_CRC1")
		if c != uint8(parser.crc.Sum16()>>8) {
			parser.state = MAVLINK_PARSE_STATE_IDLE
		} else {
			parser.state = MAVLINK_PARSE_STATE_OK
			return &parser.packet
		}
	default:
		log.Println("Ignore all switches")
	}
	return nil
}

// NewChannelDecoder function create decoder instance with default dialect
func NewChannelDecoder(data chan []byte) *Decoder {
	d := &Decoder{
		Dialects: DialectSlice{DialectCommon},
		data:     data,
	}
	return d
}

// NewDecoder function create decoder instance with default dialect
func NewDecoder(r io.Reader) *Decoder {
	d := &Decoder{
		Dialects: DialectSlice{DialectCommon},
		data:     make(chan []byte, 256),
	}
	go func() {
		for {
			bytesRead := make([]byte, 256)
			log.Println("TRY TO READ FROM READER")
			n, err := io.ReadAtLeast(r, bytesRead, 1)
			if err != nil {
				time.Sleep(time.Millisecond)
				runtime.Gosched()
			} else {
				log.Println("FROM READER NEW DATA")
				d.data <- bytesRead[:n]
			}
		}
		log.Println("FATAL: EXIT FROM READ")
	}()
	return d
}

// NewEncoder function create encoder instance with default dialect
func NewChannelEncoder(data chan []byte) *Encoder {
	e := &Encoder{
		Dialects: DialectSlice{DialectCommon},
		data:     data,
	}
	return e
}

// NewEncoder function create encoder instance with default dialect
func NewEncoder(w io.Writer) *Encoder {
	e := &Encoder{
		Dialects: DialectSlice{DialectCommon},
		data:     make(chan []byte, 256),
	}
	go func() {
		for {
			buffer := <-e.data
			w.Write(buffer)
		}
		log.Println("FATAL: EXIT FROM WRITE")
	}()
	return e
}

// helper to create packet w/header populated with received bytes
func newPacketFromBytes(b []byte) (*Packet, int) {
	return &Packet{
		InCompatFlags: b[1],
		CompatFlags:   b[2],
		SeqID:         b[3],
		SysID:         b[4],
		CompID:        b[5],
		MsgID:         MessageID(b[6] + (b[7] << 8) + (b[8] << 8 * 2)),
	}, int(b[0])
}

// Decode function reads and parses from its reader
// Typically, the caller will check the p.MsgID to see if it's
// a message they're interested in, and convert it to the
// corresponding type via Message.FromPacket()
func (dec *Decoder) Decode() (*Packet, error) {
	return dec.TimedDecode(nil)
}

// Decode function reads and parses from its reader
// Typically, the caller will check the p.MsgID to see if it's
// a message they're interested in, and convert it to the
// corresponding type via Message.FromPacket()
func (dec *Decoder) TimedDecode(duration *time.Duration) (*Packet, error) {
	started := time.Now()
	finished := started.Add(time.Hour)
	if duration != nil {
		finished = started.Add(*duration)
	}
	for {
		d := finished.Sub(time.Now())
		select {
		case buffer := <-dec.data:
			log.Println("Receive new data from channel...")
			log.Println(buffer)
			for _, c := range buffer {
				mavlinkPacket := dec.parser.parseChar(c, dec.Dialects)
				log.Printf("Char %d. Current parser state (%d)...\n", c, dec.parser.state)
				if mavlinkPacket != nil {
					return mavlinkPacket, nil
				}
			}
		case <-time.After(d):
			log.Printf("Timeout data from channel (%d)...\n", dec.parser.state)
			return nil, ErrNoNewData
		}
	}
}

// DecodeBytes function provide decode a packet from a previously received buffer (such as
// a UDP packet), b must contain a complete message
func (dec *Decoder) DecodeBytes(buffer []byte) (*Packet, error) {
	for _, c := range buffer {
		log.Printf("Current parser state (%d)...\n", dec.parser.state)
		mavlinkPacket := dec.parser.parseChar(c, dec.Dialects)
		if mavlinkPacket != nil {
			return mavlinkPacket, nil
		}
	}
	return nil, errors.New("Cannot decode bytes [ " + string(buffer[:]) + " ] code " + strconv.Itoa(int(dec.parser.state)))
}

// Encode function is a helper that accepts a Message, internally converts
// it to a Packet, sets the Packet's SeqID based on the
// and then writes it to its writer via EncodePacket()
func (enc *Encoder) Encode(sysID, compID uint8, m Message) error {
	var p Packet
	if err := m.Pack(&p); err != nil {
		return err
	}

	p.SysID, p.CompID = sysID, compID

	return enc.EncodePacket(&p)
}

// EncodePacket function provide encode writes p to its writer
func (enc *Encoder) EncodePacket(p *Packet) error {

	hdr := []byte{magicNumber, byte(len(p.Payload)), uint8(0), uint8(0), enc.CurrSeqID, p.SysID, p.CompID, uint8(p.MsgID & 0xFF), uint8((p.MsgID >> 8) & 0xFF), uint8((p.MsgID >> 16) & 0xFF)} // header
	enc.data <- hdr

	crc := x25.New()

	crc.Write(hdr[1:]) // don't include start byte

	// payload
	enc.data <- p.Payload

	crc.Write(p.Payload)

	// crc extra
	crcx, err := enc.Dialects.findCrcX(p.MsgID)
	if err != nil {
		return err
	}

	crc.WriteByte(crcx)

	// crc
	crcBytes := u16ToBytes(crc.Sum16())

	enc.data <- crcBytes

	enc.CurrSeqID++

	return err
}

func u16ToBytes(v uint16) []byte {
	return []byte{byte(v & 0xff), byte(v >> 8)}
}

func bytesToU16(p []byte) uint16 {
	// NB: does not check size of p
	return (uint16(p[1]) << 8) | uint16(p[0])
}
